// source: model/accountLedger.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_event_pb = require('../model/event_pb.js');
goog.object.extend(proto, model_event_pb);
var model_pagination_pb = require('../model/pagination_pb.js');
goog.object.extend(proto, model_pagination_pb);
goog.exportSymbol('proto.model.AccountLedger', null, global);
goog.exportSymbol('proto.model.GetAccountLedgersRequest', null, global);
goog.exportSymbol('proto.model.GetAccountLedgersResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.AccountLedger = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.AccountLedger, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.AccountLedger.displayName = 'proto.model.AccountLedger';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.GetAccountLedgersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.GetAccountLedgersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.GetAccountLedgersRequest.displayName = 'proto.model.GetAccountLedgersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.GetAccountLedgersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.model.GetAccountLedgersResponse.repeatedFields_, null);
};
goog.inherits(proto.model.GetAccountLedgersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.GetAccountLedgersResponse.displayName = 'proto.model.GetAccountLedgersResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.AccountLedger.prototype.toObject = function(opt_includeInstance) {
  return proto.model.AccountLedger.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.AccountLedger} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.AccountLedger.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountaddress: msg.getAccountaddress_asB64(),
    balancechange: jspb.Message.getFieldWithDefault(msg, 2, 0),
    blockheight: jspb.Message.getFieldWithDefault(msg, 3, 0),
    transactionid: jspb.Message.getFieldWithDefault(msg, 4, "0"),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    eventtype: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.AccountLedger}
 */
proto.model.AccountLedger.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.AccountLedger;
  return proto.model.AccountLedger.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.AccountLedger} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.AccountLedger}
 */
proto.model.AccountLedger.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAccountaddress(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBalancechange(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockheight(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readInt64String());
      msg.setTransactionid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = /** @type {!proto.model.EventType} */ (reader.readEnum());
      msg.setEventtype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.AccountLedger.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.AccountLedger.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.AccountLedger} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.AccountLedger.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountaddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getBalancechange();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getBlockheight();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getTransactionid();
  if (parseInt(f, 10) !== 0) {
    writer.writeInt64String(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getEventtype();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional bytes AccountAddress = 1;
 * @return {!(string|Uint8Array)}
 */
proto.model.AccountLedger.prototype.getAccountaddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes AccountAddress = 1;
 * This is a type-conversion wrapper around `getAccountaddress()`
 * @return {string}
 */
proto.model.AccountLedger.prototype.getAccountaddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAccountaddress()));
};


/**
 * optional bytes AccountAddress = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccountaddress()`
 * @return {!Uint8Array}
 */
proto.model.AccountLedger.prototype.getAccountaddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAccountaddress()));
};


/** @param {!(string|Uint8Array)} value */
proto.model.AccountLedger.prototype.setAccountaddress = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional int64 BalanceChange = 2;
 * @return {number}
 */
proto.model.AccountLedger.prototype.getBalancechange = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.model.AccountLedger.prototype.setBalancechange = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 BlockHeight = 3;
 * @return {number}
 */
proto.model.AccountLedger.prototype.getBlockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.model.AccountLedger.prototype.setBlockheight = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 TransactionID = 4;
 * @return {string}
 */
proto.model.AccountLedger.prototype.getTransactionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, "0"));
};


/** @param {string} value */
proto.model.AccountLedger.prototype.setTransactionid = function(value) {
  jspb.Message.setProto3StringIntField(this, 4, value);
};


/**
 * optional uint64 Timestamp = 5;
 * @return {number}
 */
proto.model.AccountLedger.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.model.AccountLedger.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional EventType EventType = 6;
 * @return {!proto.model.EventType}
 */
proto.model.AccountLedger.prototype.getEventtype = function() {
  return /** @type {!proto.model.EventType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.model.EventType} value */
proto.model.AccountLedger.prototype.setEventtype = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.GetAccountLedgersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.model.GetAccountLedgersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.GetAccountLedgersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.GetAccountLedgersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountaddress: msg.getAccountaddress_asB64(),
    eventtype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    transactionid: jspb.Message.getFieldWithDefault(msg, 3, "0"),
    timestampstart: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timestampend: jspb.Message.getFieldWithDefault(msg, 5, 0),
    pagination: (f = msg.getPagination()) && model_pagination_pb.Pagination.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.GetAccountLedgersRequest}
 */
proto.model.GetAccountLedgersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.GetAccountLedgersRequest;
  return proto.model.GetAccountLedgersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.GetAccountLedgersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.GetAccountLedgersRequest}
 */
proto.model.GetAccountLedgersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAccountaddress(value);
      break;
    case 2:
      var value = /** @type {!proto.model.EventType} */ (reader.readEnum());
      msg.setEventtype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readInt64String());
      msg.setTransactionid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestampstart(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTimestampend(value);
      break;
    case 6:
      var value = new model_pagination_pb.Pagination;
      reader.readMessage(value,model_pagination_pb.Pagination.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.GetAccountLedgersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.GetAccountLedgersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.GetAccountLedgersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.GetAccountLedgersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountaddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getEventtype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTransactionid();
  if (parseInt(f, 10) !== 0) {
    writer.writeInt64String(
      3,
      f
    );
  }
  f = message.getTimestampstart();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getTimestampend();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      model_pagination_pb.Pagination.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes AccountAddress = 1;
 * @return {!(string|Uint8Array)}
 */
proto.model.GetAccountLedgersRequest.prototype.getAccountaddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes AccountAddress = 1;
 * This is a type-conversion wrapper around `getAccountaddress()`
 * @return {string}
 */
proto.model.GetAccountLedgersRequest.prototype.getAccountaddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAccountaddress()));
};


/**
 * optional bytes AccountAddress = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccountaddress()`
 * @return {!Uint8Array}
 */
proto.model.GetAccountLedgersRequest.prototype.getAccountaddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAccountaddress()));
};


/** @param {!(string|Uint8Array)} value */
proto.model.GetAccountLedgersRequest.prototype.setAccountaddress = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional EventType EventType = 2;
 * @return {!proto.model.EventType}
 */
proto.model.GetAccountLedgersRequest.prototype.getEventtype = function() {
  return /** @type {!proto.model.EventType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.model.EventType} value */
proto.model.GetAccountLedgersRequest.prototype.setEventtype = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional int64 TransactionID = 3;
 * @return {string}
 */
proto.model.GetAccountLedgersRequest.prototype.getTransactionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, "0"));
};


/** @param {string} value */
proto.model.GetAccountLedgersRequest.prototype.setTransactionid = function(value) {
  jspb.Message.setProto3StringIntField(this, 3, value);
};


/**
 * optional uint64 TimestampStart = 4;
 * @return {number}
 */
proto.model.GetAccountLedgersRequest.prototype.getTimestampstart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.model.GetAccountLedgersRequest.prototype.setTimestampstart = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 TimestampEnd = 5;
 * @return {number}
 */
proto.model.GetAccountLedgersRequest.prototype.getTimestampend = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.model.GetAccountLedgersRequest.prototype.setTimestampend = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional Pagination Pagination = 6;
 * @return {?proto.model.Pagination}
 */
proto.model.GetAccountLedgersRequest.prototype.getPagination = function() {
  return /** @type{?proto.model.Pagination} */ (
    jspb.Message.getWrapperField(this, model_pagination_pb.Pagination, 6));
};


/** @param {?proto.model.Pagination|undefined} value */
proto.model.GetAccountLedgersRequest.prototype.setPagination = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.model.GetAccountLedgersRequest.prototype.clearPagination = function() {
  this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.GetAccountLedgersRequest.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.model.GetAccountLedgersResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.GetAccountLedgersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.model.GetAccountLedgersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.GetAccountLedgersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.GetAccountLedgersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    total: jspb.Message.getFieldWithDefault(msg, 1, "0"),
    accountledgersList: jspb.Message.toObjectList(msg.getAccountledgersList(),
    proto.model.AccountLedger.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.GetAccountLedgersResponse}
 */
proto.model.GetAccountLedgersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.GetAccountLedgersResponse;
  return proto.model.GetAccountLedgersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.GetAccountLedgersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.GetAccountLedgersResponse}
 */
proto.model.GetAccountLedgersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setTotal(value);
      break;
    case 2:
      var value = new proto.model.AccountLedger;
      reader.readMessage(value,proto.model.AccountLedger.deserializeBinaryFromReader);
      msg.addAccountledgers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.GetAccountLedgersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.GetAccountLedgersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.GetAccountLedgersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.GetAccountLedgersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTotal();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      1,
      f
    );
  }
  f = message.getAccountledgersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.model.AccountLedger.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 Total = 1;
 * @return {string}
 */
proto.model.GetAccountLedgersResponse.prototype.getTotal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, "0"));
};


/** @param {string} value */
proto.model.GetAccountLedgersResponse.prototype.setTotal = function(value) {
  jspb.Message.setProto3StringIntField(this, 1, value);
};


/**
 * repeated AccountLedger AccountLedgers = 2;
 * @return {!Array<!proto.model.AccountLedger>}
 */
proto.model.GetAccountLedgersResponse.prototype.getAccountledgersList = function() {
  return /** @type{!Array<!proto.model.AccountLedger>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.model.AccountLedger, 2));
};


/** @param {!Array<!proto.model.AccountLedger>} value */
proto.model.GetAccountLedgersResponse.prototype.setAccountledgersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.model.AccountLedger=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.AccountLedger}
 */
proto.model.GetAccountLedgersResponse.prototype.addAccountledgers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.model.AccountLedger, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.GetAccountLedgersResponse.prototype.clearAccountledgersList = function() {
  this.setAccountledgersList([]);
};


goog.object.extend(exports, proto.model);
