// package: model
// file: model/event.proto

import * as jspb from "google-protobuf";

export interface EventTypeMap {
  EVENTANY: 0;
  EVENTSENDMONEYTRANSACTION: 1;
  EVENTNODEREGISTRATIONTRANSACTION: 2;
  EVENTUPDATENODEREGISTRATIONTRANSACTION: 3;
  EVENTREMOVENODEREGISTRATIONTRANSACTION: 4;
  EVENTCLAIMNODEREGISTRATIONTRANSACTION: 5;
  EVENTSETUPACCOUNTDATASETTRANSACTION: 6;
  EVENTREMOVEACCOUNTDATASETTRANSACTION: 7;
  EVENTREWARD: 8;
  EVENTAPPROVALESCROWTRANSACTION: 9;
  EVENTMULTISIGNATURETRANSACTION: 10;
  EVENTFEEVOTECOMMITTRANSACTION: 11;
  EVENTFEEVOTEREVEALTRANSACTION: 12;
  EVENTLIQUIDPAYMENTTRANSACTION: 13;
  EVENTLIQUIDPAYMENTPAIDTRANSACTION: 14;
  EVENTLIQUIDPAYMENTSTOPTRANSACTION: 15;
  EVENTESCROWEDTRANSACTION: 16;
}

export const EventType: EventTypeMap;

