// source: model/healthCheck.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.model.GetNodeStatusResponse', null, global);
goog.exportSymbol('proto.model.HealthCheckResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.HealthCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.HealthCheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.HealthCheckResponse.displayName = 'proto.model.HealthCheckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.GetNodeStatusResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.GetNodeStatusResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.GetNodeStatusResponse.displayName = 'proto.model.GetNodeStatusResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.HealthCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.model.HealthCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.HealthCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.HealthCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    reply: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.HealthCheckResponse}
 */
proto.model.HealthCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.HealthCheckResponse;
  return proto.model.HealthCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.HealthCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.HealthCheckResponse}
 */
proto.model.HealthCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.HealthCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.HealthCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.HealthCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.HealthCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReply();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string Reply = 1;
 * @return {string}
 */
proto.model.HealthCheckResponse.prototype.getReply = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.model.HealthCheckResponse.prototype.setReply = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.GetNodeStatusResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.model.GetNodeStatusResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.GetNodeStatusResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.GetNodeStatusResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    lastmainblockheight: jspb.Message.getFieldWithDefault(msg, 1, 0),
    lastmainblockhash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastspineblockheight: jspb.Message.getFieldWithDefault(msg, 3, 0),
    lastspineblockhash: jspb.Message.getFieldWithDefault(msg, 4, ""),
    version: jspb.Message.getFieldWithDefault(msg, 5, ""),
    nodepublickey: jspb.Message.getFieldWithDefault(msg, 6, ""),
    unresolvedpeers: jspb.Message.getFieldWithDefault(msg, 7, 0),
    resolvedpeers: jspb.Message.getFieldWithDefault(msg, 8, 0),
    blocksmithindex: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.GetNodeStatusResponse}
 */
proto.model.GetNodeStatusResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.GetNodeStatusResponse;
  return proto.model.GetNodeStatusResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.GetNodeStatusResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.GetNodeStatusResponse}
 */
proto.model.GetNodeStatusResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLastmainblockheight(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastmainblockhash(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLastspineblockheight(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastspineblockhash(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodepublickey(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUnresolvedpeers(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setResolvedpeers(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlocksmithindex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.GetNodeStatusResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.GetNodeStatusResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.GetNodeStatusResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.GetNodeStatusResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLastmainblockheight();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getLastmainblockhash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastspineblockheight();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getLastspineblockhash();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNodepublickey();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUnresolvedpeers();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getResolvedpeers();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getBlocksmithindex();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
};


/**
 * optional uint32 LastMainBlockHeight = 1;
 * @return {number}
 */
proto.model.GetNodeStatusResponse.prototype.getLastmainblockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.model.GetNodeStatusResponse.prototype.setLastmainblockheight = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string LastMainBlockHash = 2;
 * @return {string}
 */
proto.model.GetNodeStatusResponse.prototype.getLastmainblockhash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.model.GetNodeStatusResponse.prototype.setLastmainblockhash = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 LastSpineBlockHeight = 3;
 * @return {number}
 */
proto.model.GetNodeStatusResponse.prototype.getLastspineblockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.model.GetNodeStatusResponse.prototype.setLastspineblockheight = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string LastSpineBlockHash = 4;
 * @return {string}
 */
proto.model.GetNodeStatusResponse.prototype.getLastspineblockhash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.model.GetNodeStatusResponse.prototype.setLastspineblockhash = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Version = 5;
 * @return {string}
 */
proto.model.GetNodeStatusResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.model.GetNodeStatusResponse.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string NodePublicKey = 6;
 * @return {string}
 */
proto.model.GetNodeStatusResponse.prototype.getNodepublickey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.model.GetNodeStatusResponse.prototype.setNodepublickey = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional uint32 UnresolvedPeers = 7;
 * @return {number}
 */
proto.model.GetNodeStatusResponse.prototype.getUnresolvedpeers = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.model.GetNodeStatusResponse.prototype.setUnresolvedpeers = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 ResolvedPeers = 8;
 * @return {number}
 */
proto.model.GetNodeStatusResponse.prototype.getResolvedpeers = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.model.GetNodeStatusResponse.prototype.setResolvedpeers = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 BlocksmithIndex = 9;
 * @return {number}
 */
proto.model.GetNodeStatusResponse.prototype.getBlocksmithindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.model.GetNodeStatusResponse.prototype.setBlocksmithindex = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


goog.object.extend(exports, proto.model);
