// source: model/snapshot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_spineBlockManifest_pb = require('../model/spineBlockManifest_pb.js');
goog.object.extend(proto, model_spineBlockManifest_pb);
var model_accountBalance_pb = require('../model/accountBalance_pb.js');
goog.object.extend(proto, model_accountBalance_pb);
var model_nodeRegistration_pb = require('../model/nodeRegistration_pb.js');
goog.object.extend(proto, model_nodeRegistration_pb);
var model_accountDataset_pb = require('../model/accountDataset_pb.js');
goog.object.extend(proto, model_accountDataset_pb);
var model_participationScore_pb = require('../model/participationScore_pb.js');
goog.object.extend(proto, model_participationScore_pb);
var model_publishedReceipt_pb = require('../model/publishedReceipt_pb.js');
goog.object.extend(proto, model_publishedReceipt_pb);
var model_escrow_pb = require('../model/escrow_pb.js');
goog.object.extend(proto, model_escrow_pb);
var model_multiSignature_pb = require('../model/multiSignature_pb.js');
goog.object.extend(proto, model_multiSignature_pb);
var model_block_pb = require('../model/block_pb.js');
goog.object.extend(proto, model_block_pb);
var model_skippedBlocksmith_pb = require('../model/skippedBlocksmith_pb.js');
goog.object.extend(proto, model_skippedBlocksmith_pb);
var model_feeScale_pb = require('../model/feeScale_pb.js');
goog.object.extend(proto, model_feeScale_pb);
var model_feeVote_pb = require('../model/feeVote_pb.js');
goog.object.extend(proto, model_feeVote_pb);
var model_liquidPayment_pb = require('../model/liquidPayment_pb.js');
goog.object.extend(proto, model_liquidPayment_pb);
goog.exportSymbol('proto.model.SnapshotFileInfo', null, global);
goog.exportSymbol('proto.model.SnapshotPayload', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.SnapshotFileInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.model.SnapshotFileInfo.repeatedFields_, null);
};
goog.inherits(proto.model.SnapshotFileInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.SnapshotFileInfo.displayName = 'proto.model.SnapshotFileInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.SnapshotPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.model.SnapshotPayload.repeatedFields_, null);
};
goog.inherits(proto.model.SnapshotPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.SnapshotPayload.displayName = 'proto.model.SnapshotPayload';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.model.SnapshotFileInfo.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.SnapshotFileInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.model.SnapshotFileInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.SnapshotFileInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SnapshotFileInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    snapshotfilehash: msg.getSnapshotfilehash_asB64(),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0),
    processexpirationtimestamp: jspb.Message.getFieldWithDefault(msg, 3, 0),
    chaintype: jspb.Message.getFieldWithDefault(msg, 4, 0),
    spineblockmanifesttype: jspb.Message.getFieldWithDefault(msg, 5, 0),
    filechunkshashesList: msg.getFilechunkshashesList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.SnapshotFileInfo}
 */
proto.model.SnapshotFileInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.SnapshotFileInfo;
  return proto.model.SnapshotFileInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.SnapshotFileInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.SnapshotFileInfo}
 */
proto.model.SnapshotFileInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSnapshotfilehash(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessexpirationtimestamp(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChaintype(value);
      break;
    case 5:
      var value = /** @type {!proto.model.SpineBlockManifestType} */ (reader.readEnum());
      msg.setSpineblockmanifesttype(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addFilechunkshashes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.SnapshotFileInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.SnapshotFileInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.SnapshotFileInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SnapshotFileInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSnapshotfilehash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getProcessexpirationtimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getChaintype();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSpineblockmanifesttype();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getFilechunkshashesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      6,
      f
    );
  }
};


/**
 * optional bytes SnapshotFileHash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.model.SnapshotFileInfo.prototype.getSnapshotfilehash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes SnapshotFileHash = 1;
 * This is a type-conversion wrapper around `getSnapshotfilehash()`
 * @return {string}
 */
proto.model.SnapshotFileInfo.prototype.getSnapshotfilehash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSnapshotfilehash()));
};


/**
 * optional bytes SnapshotFileHash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSnapshotfilehash()`
 * @return {!Uint8Array}
 */
proto.model.SnapshotFileInfo.prototype.getSnapshotfilehash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSnapshotfilehash()));
};


/** @param {!(string|Uint8Array)} value */
proto.model.SnapshotFileInfo.prototype.setSnapshotfilehash = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional uint32 Height = 2;
 * @return {number}
 */
proto.model.SnapshotFileInfo.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.model.SnapshotFileInfo.prototype.setHeight = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 ProcessExpirationTimestamp = 3;
 * @return {number}
 */
proto.model.SnapshotFileInfo.prototype.getProcessexpirationtimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.model.SnapshotFileInfo.prototype.setProcessexpirationtimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 ChainType = 4;
 * @return {number}
 */
proto.model.SnapshotFileInfo.prototype.getChaintype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.model.SnapshotFileInfo.prototype.setChaintype = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional SpineBlockManifestType SpineBlockManifestType = 5;
 * @return {!proto.model.SpineBlockManifestType}
 */
proto.model.SnapshotFileInfo.prototype.getSpineblockmanifesttype = function() {
  return /** @type {!proto.model.SpineBlockManifestType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.model.SpineBlockManifestType} value */
proto.model.SnapshotFileInfo.prototype.setSpineblockmanifesttype = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * repeated bytes FileChunksHashes = 6;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.model.SnapshotFileInfo.prototype.getFilechunkshashesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * repeated bytes FileChunksHashes = 6;
 * This is a type-conversion wrapper around `getFilechunkshashesList()`
 * @return {!Array<string>}
 */
proto.model.SnapshotFileInfo.prototype.getFilechunkshashesList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getFilechunkshashesList()));
};


/**
 * repeated bytes FileChunksHashes = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFilechunkshashesList()`
 * @return {!Array<!Uint8Array>}
 */
proto.model.SnapshotFileInfo.prototype.getFilechunkshashesList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getFilechunkshashesList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.model.SnapshotFileInfo.prototype.setFilechunkshashesList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.model.SnapshotFileInfo.prototype.addFilechunkshashes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotFileInfo.prototype.clearFilechunkshashesList = function() {
  this.setFilechunkshashesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.model.SnapshotPayload.repeatedFields_ = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.SnapshotPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.model.SnapshotPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.SnapshotPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SnapshotPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    blocksList: jspb.Message.toObjectList(msg.getBlocksList(),
    model_block_pb.Block.toObject, includeInstance),
    accountbalancesList: jspb.Message.toObjectList(msg.getAccountbalancesList(),
    model_accountBalance_pb.AccountBalance.toObject, includeInstance),
    noderegistrationsList: jspb.Message.toObjectList(msg.getNoderegistrationsList(),
    model_nodeRegistration_pb.NodeRegistration.toObject, includeInstance),
    accountdatasetsList: jspb.Message.toObjectList(msg.getAccountdatasetsList(),
    model_accountDataset_pb.AccountDataset.toObject, includeInstance),
    participationscoresList: jspb.Message.toObjectList(msg.getParticipationscoresList(),
    model_participationScore_pb.ParticipationScore.toObject, includeInstance),
    publishedreceiptsList: jspb.Message.toObjectList(msg.getPublishedreceiptsList(),
    model_publishedReceipt_pb.PublishedReceipt.toObject, includeInstance),
    escrowtransactionsList: jspb.Message.toObjectList(msg.getEscrowtransactionsList(),
    model_escrow_pb.Escrow.toObject, includeInstance),
    pendingtransactionsList: jspb.Message.toObjectList(msg.getPendingtransactionsList(),
    model_multiSignature_pb.PendingTransaction.toObject, includeInstance),
    pendingsignaturesList: jspb.Message.toObjectList(msg.getPendingsignaturesList(),
    model_multiSignature_pb.PendingSignature.toObject, includeInstance),
    multisignatureinfosList: jspb.Message.toObjectList(msg.getMultisignatureinfosList(),
    model_multiSignature_pb.MultiSignatureInfo.toObject, includeInstance),
    skippedblocksmithsList: jspb.Message.toObjectList(msg.getSkippedblocksmithsList(),
    model_skippedBlocksmith_pb.SkippedBlocksmith.toObject, includeInstance),
    feescaleList: jspb.Message.toObjectList(msg.getFeescaleList(),
    model_feeScale_pb.FeeScale.toObject, includeInstance),
    feevotecommitmentvoteList: jspb.Message.toObjectList(msg.getFeevotecommitmentvoteList(),
    model_feeVote_pb.FeeVoteCommitmentVote.toObject, includeInstance),
    feevoterevealvoteList: jspb.Message.toObjectList(msg.getFeevoterevealvoteList(),
    model_feeVote_pb.FeeVoteRevealVote.toObject, includeInstance),
    liquidpaymentList: jspb.Message.toObjectList(msg.getLiquidpaymentList(),
    model_liquidPayment_pb.LiquidPayment.toObject, includeInstance),
    nodeadmissiontimestampList: jspb.Message.toObjectList(msg.getNodeadmissiontimestampList(),
    model_nodeRegistration_pb.NodeAdmissionTimestamp.toObject, includeInstance),
    multisignatureparticipantsList: jspb.Message.toObjectList(msg.getMultisignatureparticipantsList(),
    model_multiSignature_pb.MultiSignatureParticipant.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.SnapshotPayload}
 */
proto.model.SnapshotPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.SnapshotPayload;
  return proto.model.SnapshotPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.SnapshotPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.SnapshotPayload}
 */
proto.model.SnapshotPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new model_block_pb.Block;
      reader.readMessage(value,model_block_pb.Block.deserializeBinaryFromReader);
      msg.addBlocks(value);
      break;
    case 2:
      var value = new model_accountBalance_pb.AccountBalance;
      reader.readMessage(value,model_accountBalance_pb.AccountBalance.deserializeBinaryFromReader);
      msg.addAccountbalances(value);
      break;
    case 3:
      var value = new model_nodeRegistration_pb.NodeRegistration;
      reader.readMessage(value,model_nodeRegistration_pb.NodeRegistration.deserializeBinaryFromReader);
      msg.addNoderegistrations(value);
      break;
    case 4:
      var value = new model_accountDataset_pb.AccountDataset;
      reader.readMessage(value,model_accountDataset_pb.AccountDataset.deserializeBinaryFromReader);
      msg.addAccountdatasets(value);
      break;
    case 5:
      var value = new model_participationScore_pb.ParticipationScore;
      reader.readMessage(value,model_participationScore_pb.ParticipationScore.deserializeBinaryFromReader);
      msg.addParticipationscores(value);
      break;
    case 6:
      var value = new model_publishedReceipt_pb.PublishedReceipt;
      reader.readMessage(value,model_publishedReceipt_pb.PublishedReceipt.deserializeBinaryFromReader);
      msg.addPublishedreceipts(value);
      break;
    case 7:
      var value = new model_escrow_pb.Escrow;
      reader.readMessage(value,model_escrow_pb.Escrow.deserializeBinaryFromReader);
      msg.addEscrowtransactions(value);
      break;
    case 8:
      var value = new model_multiSignature_pb.PendingTransaction;
      reader.readMessage(value,model_multiSignature_pb.PendingTransaction.deserializeBinaryFromReader);
      msg.addPendingtransactions(value);
      break;
    case 9:
      var value = new model_multiSignature_pb.PendingSignature;
      reader.readMessage(value,model_multiSignature_pb.PendingSignature.deserializeBinaryFromReader);
      msg.addPendingsignatures(value);
      break;
    case 10:
      var value = new model_multiSignature_pb.MultiSignatureInfo;
      reader.readMessage(value,model_multiSignature_pb.MultiSignatureInfo.deserializeBinaryFromReader);
      msg.addMultisignatureinfos(value);
      break;
    case 11:
      var value = new model_skippedBlocksmith_pb.SkippedBlocksmith;
      reader.readMessage(value,model_skippedBlocksmith_pb.SkippedBlocksmith.deserializeBinaryFromReader);
      msg.addSkippedblocksmiths(value);
      break;
    case 12:
      var value = new model_feeScale_pb.FeeScale;
      reader.readMessage(value,model_feeScale_pb.FeeScale.deserializeBinaryFromReader);
      msg.addFeescale(value);
      break;
    case 13:
      var value = new model_feeVote_pb.FeeVoteCommitmentVote;
      reader.readMessage(value,model_feeVote_pb.FeeVoteCommitmentVote.deserializeBinaryFromReader);
      msg.addFeevotecommitmentvote(value);
      break;
    case 14:
      var value = new model_feeVote_pb.FeeVoteRevealVote;
      reader.readMessage(value,model_feeVote_pb.FeeVoteRevealVote.deserializeBinaryFromReader);
      msg.addFeevoterevealvote(value);
      break;
    case 15:
      var value = new model_liquidPayment_pb.LiquidPayment;
      reader.readMessage(value,model_liquidPayment_pb.LiquidPayment.deserializeBinaryFromReader);
      msg.addLiquidpayment(value);
      break;
    case 16:
      var value = new model_nodeRegistration_pb.NodeAdmissionTimestamp;
      reader.readMessage(value,model_nodeRegistration_pb.NodeAdmissionTimestamp.deserializeBinaryFromReader);
      msg.addNodeadmissiontimestamp(value);
      break;
    case 17:
      var value = new model_multiSignature_pb.MultiSignatureParticipant;
      reader.readMessage(value,model_multiSignature_pb.MultiSignatureParticipant.deserializeBinaryFromReader);
      msg.addMultisignatureparticipants(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.SnapshotPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.SnapshotPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.SnapshotPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SnapshotPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlocksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      model_block_pb.Block.serializeBinaryToWriter
    );
  }
  f = message.getAccountbalancesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      model_accountBalance_pb.AccountBalance.serializeBinaryToWriter
    );
  }
  f = message.getNoderegistrationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      model_nodeRegistration_pb.NodeRegistration.serializeBinaryToWriter
    );
  }
  f = message.getAccountdatasetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      model_accountDataset_pb.AccountDataset.serializeBinaryToWriter
    );
  }
  f = message.getParticipationscoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      model_participationScore_pb.ParticipationScore.serializeBinaryToWriter
    );
  }
  f = message.getPublishedreceiptsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      model_publishedReceipt_pb.PublishedReceipt.serializeBinaryToWriter
    );
  }
  f = message.getEscrowtransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      model_escrow_pb.Escrow.serializeBinaryToWriter
    );
  }
  f = message.getPendingtransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      model_multiSignature_pb.PendingTransaction.serializeBinaryToWriter
    );
  }
  f = message.getPendingsignaturesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      model_multiSignature_pb.PendingSignature.serializeBinaryToWriter
    );
  }
  f = message.getMultisignatureinfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      model_multiSignature_pb.MultiSignatureInfo.serializeBinaryToWriter
    );
  }
  f = message.getSkippedblocksmithsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      model_skippedBlocksmith_pb.SkippedBlocksmith.serializeBinaryToWriter
    );
  }
  f = message.getFeescaleList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      model_feeScale_pb.FeeScale.serializeBinaryToWriter
    );
  }
  f = message.getFeevotecommitmentvoteList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      model_feeVote_pb.FeeVoteCommitmentVote.serializeBinaryToWriter
    );
  }
  f = message.getFeevoterevealvoteList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      model_feeVote_pb.FeeVoteRevealVote.serializeBinaryToWriter
    );
  }
  f = message.getLiquidpaymentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      model_liquidPayment_pb.LiquidPayment.serializeBinaryToWriter
    );
  }
  f = message.getNodeadmissiontimestampList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      model_nodeRegistration_pb.NodeAdmissionTimestamp.serializeBinaryToWriter
    );
  }
  f = message.getMultisignatureparticipantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      17,
      f,
      model_multiSignature_pb.MultiSignatureParticipant.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Block Blocks = 1;
 * @return {!Array<!proto.model.Block>}
 */
proto.model.SnapshotPayload.prototype.getBlocksList = function() {
  return /** @type{!Array<!proto.model.Block>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_block_pb.Block, 1));
};


/** @param {!Array<!proto.model.Block>} value */
proto.model.SnapshotPayload.prototype.setBlocksList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.model.Block=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.Block}
 */
proto.model.SnapshotPayload.prototype.addBlocks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.model.Block, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearBlocksList = function() {
  this.setBlocksList([]);
};


/**
 * repeated AccountBalance AccountBalances = 2;
 * @return {!Array<!proto.model.AccountBalance>}
 */
proto.model.SnapshotPayload.prototype.getAccountbalancesList = function() {
  return /** @type{!Array<!proto.model.AccountBalance>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_accountBalance_pb.AccountBalance, 2));
};


/** @param {!Array<!proto.model.AccountBalance>} value */
proto.model.SnapshotPayload.prototype.setAccountbalancesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.model.AccountBalance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.AccountBalance}
 */
proto.model.SnapshotPayload.prototype.addAccountbalances = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.model.AccountBalance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearAccountbalancesList = function() {
  this.setAccountbalancesList([]);
};


/**
 * repeated NodeRegistration NodeRegistrations = 3;
 * @return {!Array<!proto.model.NodeRegistration>}
 */
proto.model.SnapshotPayload.prototype.getNoderegistrationsList = function() {
  return /** @type{!Array<!proto.model.NodeRegistration>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_nodeRegistration_pb.NodeRegistration, 3));
};


/** @param {!Array<!proto.model.NodeRegistration>} value */
proto.model.SnapshotPayload.prototype.setNoderegistrationsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.model.NodeRegistration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.NodeRegistration}
 */
proto.model.SnapshotPayload.prototype.addNoderegistrations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.model.NodeRegistration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearNoderegistrationsList = function() {
  this.setNoderegistrationsList([]);
};


/**
 * repeated AccountDataset AccountDatasets = 4;
 * @return {!Array<!proto.model.AccountDataset>}
 */
proto.model.SnapshotPayload.prototype.getAccountdatasetsList = function() {
  return /** @type{!Array<!proto.model.AccountDataset>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_accountDataset_pb.AccountDataset, 4));
};


/** @param {!Array<!proto.model.AccountDataset>} value */
proto.model.SnapshotPayload.prototype.setAccountdatasetsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.model.AccountDataset=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.AccountDataset}
 */
proto.model.SnapshotPayload.prototype.addAccountdatasets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.model.AccountDataset, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearAccountdatasetsList = function() {
  this.setAccountdatasetsList([]);
};


/**
 * repeated ParticipationScore ParticipationScores = 5;
 * @return {!Array<!proto.model.ParticipationScore>}
 */
proto.model.SnapshotPayload.prototype.getParticipationscoresList = function() {
  return /** @type{!Array<!proto.model.ParticipationScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_participationScore_pb.ParticipationScore, 5));
};


/** @param {!Array<!proto.model.ParticipationScore>} value */
proto.model.SnapshotPayload.prototype.setParticipationscoresList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.model.ParticipationScore=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.ParticipationScore}
 */
proto.model.SnapshotPayload.prototype.addParticipationscores = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.model.ParticipationScore, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearParticipationscoresList = function() {
  this.setParticipationscoresList([]);
};


/**
 * repeated PublishedReceipt PublishedReceipts = 6;
 * @return {!Array<!proto.model.PublishedReceipt>}
 */
proto.model.SnapshotPayload.prototype.getPublishedreceiptsList = function() {
  return /** @type{!Array<!proto.model.PublishedReceipt>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_publishedReceipt_pb.PublishedReceipt, 6));
};


/** @param {!Array<!proto.model.PublishedReceipt>} value */
proto.model.SnapshotPayload.prototype.setPublishedreceiptsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.model.PublishedReceipt=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.PublishedReceipt}
 */
proto.model.SnapshotPayload.prototype.addPublishedreceipts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.model.PublishedReceipt, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearPublishedreceiptsList = function() {
  this.setPublishedreceiptsList([]);
};


/**
 * repeated Escrow EscrowTransactions = 7;
 * @return {!Array<!proto.model.Escrow>}
 */
proto.model.SnapshotPayload.prototype.getEscrowtransactionsList = function() {
  return /** @type{!Array<!proto.model.Escrow>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_escrow_pb.Escrow, 7));
};


/** @param {!Array<!proto.model.Escrow>} value */
proto.model.SnapshotPayload.prototype.setEscrowtransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.model.Escrow=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.Escrow}
 */
proto.model.SnapshotPayload.prototype.addEscrowtransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.model.Escrow, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearEscrowtransactionsList = function() {
  this.setEscrowtransactionsList([]);
};


/**
 * repeated PendingTransaction PendingTransactions = 8;
 * @return {!Array<!proto.model.PendingTransaction>}
 */
proto.model.SnapshotPayload.prototype.getPendingtransactionsList = function() {
  return /** @type{!Array<!proto.model.PendingTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_multiSignature_pb.PendingTransaction, 8));
};


/** @param {!Array<!proto.model.PendingTransaction>} value */
proto.model.SnapshotPayload.prototype.setPendingtransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.model.PendingTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.PendingTransaction}
 */
proto.model.SnapshotPayload.prototype.addPendingtransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.model.PendingTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearPendingtransactionsList = function() {
  this.setPendingtransactionsList([]);
};


/**
 * repeated PendingSignature PendingSignatures = 9;
 * @return {!Array<!proto.model.PendingSignature>}
 */
proto.model.SnapshotPayload.prototype.getPendingsignaturesList = function() {
  return /** @type{!Array<!proto.model.PendingSignature>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_multiSignature_pb.PendingSignature, 9));
};


/** @param {!Array<!proto.model.PendingSignature>} value */
proto.model.SnapshotPayload.prototype.setPendingsignaturesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.model.PendingSignature=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.PendingSignature}
 */
proto.model.SnapshotPayload.prototype.addPendingsignatures = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.model.PendingSignature, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearPendingsignaturesList = function() {
  this.setPendingsignaturesList([]);
};


/**
 * repeated MultiSignatureInfo MultiSignatureInfos = 10;
 * @return {!Array<!proto.model.MultiSignatureInfo>}
 */
proto.model.SnapshotPayload.prototype.getMultisignatureinfosList = function() {
  return /** @type{!Array<!proto.model.MultiSignatureInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_multiSignature_pb.MultiSignatureInfo, 10));
};


/** @param {!Array<!proto.model.MultiSignatureInfo>} value */
proto.model.SnapshotPayload.prototype.setMultisignatureinfosList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.model.MultiSignatureInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.MultiSignatureInfo}
 */
proto.model.SnapshotPayload.prototype.addMultisignatureinfos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.model.MultiSignatureInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearMultisignatureinfosList = function() {
  this.setMultisignatureinfosList([]);
};


/**
 * repeated SkippedBlocksmith SkippedBlocksmiths = 11;
 * @return {!Array<!proto.model.SkippedBlocksmith>}
 */
proto.model.SnapshotPayload.prototype.getSkippedblocksmithsList = function() {
  return /** @type{!Array<!proto.model.SkippedBlocksmith>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_skippedBlocksmith_pb.SkippedBlocksmith, 11));
};


/** @param {!Array<!proto.model.SkippedBlocksmith>} value */
proto.model.SnapshotPayload.prototype.setSkippedblocksmithsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.model.SkippedBlocksmith=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.SkippedBlocksmith}
 */
proto.model.SnapshotPayload.prototype.addSkippedblocksmiths = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.model.SkippedBlocksmith, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearSkippedblocksmithsList = function() {
  this.setSkippedblocksmithsList([]);
};


/**
 * repeated FeeScale FeeScale = 12;
 * @return {!Array<!proto.model.FeeScale>}
 */
proto.model.SnapshotPayload.prototype.getFeescaleList = function() {
  return /** @type{!Array<!proto.model.FeeScale>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_feeScale_pb.FeeScale, 12));
};


/** @param {!Array<!proto.model.FeeScale>} value */
proto.model.SnapshotPayload.prototype.setFeescaleList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.model.FeeScale=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.FeeScale}
 */
proto.model.SnapshotPayload.prototype.addFeescale = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.model.FeeScale, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearFeescaleList = function() {
  this.setFeescaleList([]);
};


/**
 * repeated FeeVoteCommitmentVote FeeVoteCommitmentVote = 13;
 * @return {!Array<!proto.model.FeeVoteCommitmentVote>}
 */
proto.model.SnapshotPayload.prototype.getFeevotecommitmentvoteList = function() {
  return /** @type{!Array<!proto.model.FeeVoteCommitmentVote>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_feeVote_pb.FeeVoteCommitmentVote, 13));
};


/** @param {!Array<!proto.model.FeeVoteCommitmentVote>} value */
proto.model.SnapshotPayload.prototype.setFeevotecommitmentvoteList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.model.FeeVoteCommitmentVote=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.FeeVoteCommitmentVote}
 */
proto.model.SnapshotPayload.prototype.addFeevotecommitmentvote = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.model.FeeVoteCommitmentVote, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearFeevotecommitmentvoteList = function() {
  this.setFeevotecommitmentvoteList([]);
};


/**
 * repeated FeeVoteRevealVote FeeVoteRevealVote = 14;
 * @return {!Array<!proto.model.FeeVoteRevealVote>}
 */
proto.model.SnapshotPayload.prototype.getFeevoterevealvoteList = function() {
  return /** @type{!Array<!proto.model.FeeVoteRevealVote>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_feeVote_pb.FeeVoteRevealVote, 14));
};


/** @param {!Array<!proto.model.FeeVoteRevealVote>} value */
proto.model.SnapshotPayload.prototype.setFeevoterevealvoteList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.model.FeeVoteRevealVote=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.FeeVoteRevealVote}
 */
proto.model.SnapshotPayload.prototype.addFeevoterevealvote = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.model.FeeVoteRevealVote, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearFeevoterevealvoteList = function() {
  this.setFeevoterevealvoteList([]);
};


/**
 * repeated LiquidPayment LiquidPayment = 15;
 * @return {!Array<!proto.model.LiquidPayment>}
 */
proto.model.SnapshotPayload.prototype.getLiquidpaymentList = function() {
  return /** @type{!Array<!proto.model.LiquidPayment>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_liquidPayment_pb.LiquidPayment, 15));
};


/** @param {!Array<!proto.model.LiquidPayment>} value */
proto.model.SnapshotPayload.prototype.setLiquidpaymentList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.model.LiquidPayment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.LiquidPayment}
 */
proto.model.SnapshotPayload.prototype.addLiquidpayment = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.model.LiquidPayment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearLiquidpaymentList = function() {
  this.setLiquidpaymentList([]);
};


/**
 * repeated NodeAdmissionTimestamp NodeAdmissionTimestamp = 16;
 * @return {!Array<!proto.model.NodeAdmissionTimestamp>}
 */
proto.model.SnapshotPayload.prototype.getNodeadmissiontimestampList = function() {
  return /** @type{!Array<!proto.model.NodeAdmissionTimestamp>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_nodeRegistration_pb.NodeAdmissionTimestamp, 16));
};


/** @param {!Array<!proto.model.NodeAdmissionTimestamp>} value */
proto.model.SnapshotPayload.prototype.setNodeadmissiontimestampList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.model.NodeAdmissionTimestamp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.NodeAdmissionTimestamp}
 */
proto.model.SnapshotPayload.prototype.addNodeadmissiontimestamp = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.model.NodeAdmissionTimestamp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearNodeadmissiontimestampList = function() {
  this.setNodeadmissiontimestampList([]);
};


/**
 * repeated MultiSignatureParticipant MultiSignatureParticipants = 17;
 * @return {!Array<!proto.model.MultiSignatureParticipant>}
 */
proto.model.SnapshotPayload.prototype.getMultisignatureparticipantsList = function() {
  return /** @type{!Array<!proto.model.MultiSignatureParticipant>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_multiSignature_pb.MultiSignatureParticipant, 17));
};


/** @param {!Array<!proto.model.MultiSignatureParticipant>} value */
proto.model.SnapshotPayload.prototype.setMultisignatureparticipantsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 17, value);
};


/**
 * @param {!proto.model.MultiSignatureParticipant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.model.MultiSignatureParticipant}
 */
proto.model.SnapshotPayload.prototype.addMultisignatureparticipants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, proto.model.MultiSignatureParticipant, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.model.SnapshotPayload.prototype.clearMultisignatureparticipantsList = function() {
  this.setMultisignatureparticipantsList([]);
};


goog.object.extend(exports, proto.model);
