// source: model/spineBlockManifest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.model.SpineBlockManifest', null, global);
goog.exportSymbol('proto.model.SpineBlockManifestType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.SpineBlockManifest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.SpineBlockManifest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.SpineBlockManifest.displayName = 'proto.model.SpineBlockManifest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.SpineBlockManifest.prototype.toObject = function(opt_includeInstance) {
  return proto.model.SpineBlockManifest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.SpineBlockManifest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SpineBlockManifest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "0"),
    fullfilehash: msg.getFullfilehash_asB64(),
    filechunkhashes: msg.getFilechunkhashes_asB64(),
    manifestreferenceheight: jspb.Message.getFieldWithDefault(msg, 4, 0),
    manifestspineblockheight: jspb.Message.getFieldWithDefault(msg, 5, 0),
    chaintype: jspb.Message.getFieldWithDefault(msg, 6, 0),
    spineblockmanifesttype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    expirationtimestamp: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.SpineBlockManifest}
 */
proto.model.SpineBlockManifest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.SpineBlockManifest;
  return proto.model.SpineBlockManifest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.SpineBlockManifest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.SpineBlockManifest}
 */
proto.model.SpineBlockManifest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readInt64String());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFullfilehash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFilechunkhashes(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setManifestreferenceheight(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setManifestspineblockheight(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChaintype(value);
      break;
    case 7:
      var value = /** @type {!proto.model.SpineBlockManifestType} */ (reader.readEnum());
      msg.setSpineblockmanifesttype(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpirationtimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.SpineBlockManifest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.SpineBlockManifest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.SpineBlockManifest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SpineBlockManifest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (parseInt(f, 10) !== 0) {
    writer.writeInt64String(
      1,
      f
    );
  }
  f = message.getFullfilehash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getFilechunkhashes_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getManifestreferenceheight();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getManifestspineblockheight();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getChaintype();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getSpineblockmanifesttype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getExpirationtimestamp();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
};


/**
 * optional int64 ID = 1;
 * @return {string}
 */
proto.model.SpineBlockManifest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, "0"));
};


/** @param {string} value */
proto.model.SpineBlockManifest.prototype.setId = function(value) {
  jspb.Message.setProto3StringIntField(this, 1, value);
};


/**
 * optional bytes FullFileHash = 2;
 * @return {!(string|Uint8Array)}
 */
proto.model.SpineBlockManifest.prototype.getFullfilehash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes FullFileHash = 2;
 * This is a type-conversion wrapper around `getFullfilehash()`
 * @return {string}
 */
proto.model.SpineBlockManifest.prototype.getFullfilehash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFullfilehash()));
};


/**
 * optional bytes FullFileHash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFullfilehash()`
 * @return {!Uint8Array}
 */
proto.model.SpineBlockManifest.prototype.getFullfilehash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFullfilehash()));
};


/** @param {!(string|Uint8Array)} value */
proto.model.SpineBlockManifest.prototype.setFullfilehash = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes FileChunkHashes = 3;
 * @return {!(string|Uint8Array)}
 */
proto.model.SpineBlockManifest.prototype.getFilechunkhashes = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes FileChunkHashes = 3;
 * This is a type-conversion wrapper around `getFilechunkhashes()`
 * @return {string}
 */
proto.model.SpineBlockManifest.prototype.getFilechunkhashes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFilechunkhashes()));
};


/**
 * optional bytes FileChunkHashes = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFilechunkhashes()`
 * @return {!Uint8Array}
 */
proto.model.SpineBlockManifest.prototype.getFilechunkhashes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFilechunkhashes()));
};


/** @param {!(string|Uint8Array)} value */
proto.model.SpineBlockManifest.prototype.setFilechunkhashes = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional uint32 ManifestReferenceHeight = 4;
 * @return {number}
 */
proto.model.SpineBlockManifest.prototype.getManifestreferenceheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.model.SpineBlockManifest.prototype.setManifestreferenceheight = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 ManifestSpineBlockHeight = 5;
 * @return {number}
 */
proto.model.SpineBlockManifest.prototype.getManifestspineblockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.model.SpineBlockManifest.prototype.setManifestspineblockheight = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 ChainType = 6;
 * @return {number}
 */
proto.model.SpineBlockManifest.prototype.getChaintype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.model.SpineBlockManifest.prototype.setChaintype = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional SpineBlockManifestType SpineBlockManifestType = 7;
 * @return {!proto.model.SpineBlockManifestType}
 */
proto.model.SpineBlockManifest.prototype.getSpineblockmanifesttype = function() {
  return /** @type {!proto.model.SpineBlockManifestType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.model.SpineBlockManifestType} value */
proto.model.SpineBlockManifest.prototype.setSpineblockmanifesttype = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional int64 ExpirationTimestamp = 8;
 * @return {number}
 */
proto.model.SpineBlockManifest.prototype.getExpirationtimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.model.SpineBlockManifest.prototype.setExpirationtimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * @enum {number}
 */
proto.model.SpineBlockManifestType = {
  SNAPSHOT: 0
};

goog.object.extend(exports, proto.model);
