// source: model/host.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_node_pb = require('../model/node_pb.js');
goog.object.extend(proto, model_node_pb);
var model_peer_pb = require('../model/peer_pb.js');
goog.object.extend(proto, model_peer_pb);
goog.exportSymbol('proto.model.Host', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.Host = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.Host, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.Host.displayName = 'proto.model.Host';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.Host.prototype.toObject = function(opt_includeInstance) {
  return proto.model.Host.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.Host} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.Host.toObject = function(includeInstance, msg) {
  var f, obj = {
    info: (f = msg.getInfo()) && model_node_pb.Node.toObject(includeInstance, f),
    resolvedpeersMap: (f = msg.getResolvedpeersMap()) ? f.toObject(includeInstance, proto.model.Peer.toObject) : [],
    unresolvedpeersMap: (f = msg.getUnresolvedpeersMap()) ? f.toObject(includeInstance, proto.model.Peer.toObject) : [],
    knownpeersMap: (f = msg.getKnownpeersMap()) ? f.toObject(includeInstance, proto.model.Peer.toObject) : [],
    blacklistedpeersMap: (f = msg.getBlacklistedpeersMap()) ? f.toObject(includeInstance, proto.model.Peer.toObject) : [],
    stopped: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.Host}
 */
proto.model.Host.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.Host;
  return proto.model.Host.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.Host} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.Host}
 */
proto.model.Host.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new model_node_pb.Node;
      reader.readMessage(value,model_node_pb.Node.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    case 2:
      var value = msg.getResolvedpeersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.model.Peer.deserializeBinaryFromReader, "");
         });
      break;
    case 3:
      var value = msg.getUnresolvedpeersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.model.Peer.deserializeBinaryFromReader, "");
         });
      break;
    case 4:
      var value = msg.getKnownpeersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.model.Peer.deserializeBinaryFromReader, "");
         });
      break;
    case 5:
      var value = msg.getBlacklistedpeersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.model.Peer.deserializeBinaryFromReader, "");
         });
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStopped(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.Host.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.Host.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.Host} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.Host.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      model_node_pb.Node.serializeBinaryToWriter
    );
  }
  f = message.getResolvedpeersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.model.Peer.serializeBinaryToWriter);
  }
  f = message.getUnresolvedpeersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.model.Peer.serializeBinaryToWriter);
  }
  f = message.getKnownpeersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.model.Peer.serializeBinaryToWriter);
  }
  f = message.getBlacklistedpeersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.model.Peer.serializeBinaryToWriter);
  }
  f = message.getStopped();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional Node Info = 1;
 * @return {?proto.model.Node}
 */
proto.model.Host.prototype.getInfo = function() {
  return /** @type{?proto.model.Node} */ (
    jspb.Message.getWrapperField(this, model_node_pb.Node, 1));
};


/** @param {?proto.model.Node|undefined} value */
proto.model.Host.prototype.setInfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.model.Host.prototype.clearInfo = function() {
  this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.Host.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<string, Peer> ResolvedPeers = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.model.Peer>}
 */
proto.model.Host.prototype.getResolvedpeersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.model.Peer>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.model.Peer));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.model.Host.prototype.clearResolvedpeersMap = function() {
  this.getResolvedpeersMap().clear();
};


/**
 * map<string, Peer> UnresolvedPeers = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.model.Peer>}
 */
proto.model.Host.prototype.getUnresolvedpeersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.model.Peer>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.model.Peer));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.model.Host.prototype.clearUnresolvedpeersMap = function() {
  this.getUnresolvedpeersMap().clear();
};


/**
 * map<string, Peer> KnownPeers = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.model.Peer>}
 */
proto.model.Host.prototype.getKnownpeersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.model.Peer>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.model.Peer));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.model.Host.prototype.clearKnownpeersMap = function() {
  this.getKnownpeersMap().clear();
};


/**
 * map<string, Peer> BlacklistedPeers = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.model.Peer>}
 */
proto.model.Host.prototype.getBlacklistedpeersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.model.Peer>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      proto.model.Peer));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.model.Host.prototype.clearBlacklistedpeersMap = function() {
  this.getBlacklistedpeersMap().clear();
};


/**
 * optional bool Stopped = 6;
 * @return {boolean}
 */
proto.model.Host.prototype.getStopped = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.model.Host.prototype.setStopped = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


goog.object.extend(exports, proto.model);
